const fs=require('fs'),assert=require('assert');const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const c=await b.newContext({viewport:{width:1365,height:900}});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('ewa-language','en'));const outputs=[];
const grab=async selector=>{await p.waitForTimeout(80);outputs.push(await p.locator(selector).innerText())};
await p.goto('http://127.0.0.1:8767/en/admin.html');await p.waitForTimeout(1000);await p.locator('#admin-password').fill('wrong');await p.locator('#admin-form button').click();await grab('#admin-error');const pass=await p.evaluate(()=>{const d=new Date();return ''+d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')});await p.locator('#admin-password').fill(pass);await p.locator('#admin-form button').click();
for(const id of ['nv-calc','calc-full','calc-micro','calc-names','ap-calc','a9-calc','rel-calc','child-calc','career-calc','biz-calc','start-calc'])await p.locator('#'+id).click();await grab('#main-content');
for(const id of ['nv-first','full-name','name-a','rel-name-a','child-name','career-name'])await p.locator('#'+id).fill('Anna');for(const id of ['nv-surname','name-b','rel-name-b'])await p.locator('#'+id).fill('Smith');
for(const id of ['birth-date','micro-date','period-date','name-date','ap-birth','a9-birth','rel-date-a','rel-date-b','child-date','career-date','start-owner'])await p.locator('#'+id).fill('1990-05-17');await p.locator('.biz-name').first().fill('Studio');await p.locator('.start-date').first().fill('2027-01-12');
for(const id of ['nv-calc','calc-full','calc-micro','calc-period','calc-names','ap-calc','a9-calc','rel-calc','child-calc','career-calc','biz-calc','start-calc'])await p.locator('#'+id).click();await grab('#main-content');
await p.locator('#photo-search-id').fill('001');await p.locator('#photo-search-form button').click();await p.locator('#photo-search-result img').waitFor();await p.waitForTimeout(100);assert(await p.locator('#photo-search-result img').evaluate(e=>e.complete&&e.naturalWidth>0));await grab('#photo-search-result');await p.locator('#photo-search-id').fill('025');await p.locator('#photo-search-form button').click();await grab('#photo-search-result');
await p.goto('http://127.0.0.1:8767/en/tworczosc.html');await p.locator('.art-gallery-item').first().click();assert.match(await p.locator('dialog[open] code').innerText(),/image_id_\d+/);await p.locator('dialog[open] .art-gallery-next').click();await p.locator('dialog[open] .art-gallery-close').click();await p.locator('[data-gallery-filter]').nth(2).click();await grab('.art-gallery-filters');
await p.goto('http://127.0.0.1:8767/en/oferta-2026.html');await p.locator('#offer26-password').fill(pass);await p.locator('#offer26-gate-form button').click();await p.locator('[data-preview]').first().click();await grab('#offer26-products');for(const button of await p.locator('#offer26-filter button').all())await button.click();await grab('#offer26-products');
await p.goto('http://127.0.0.1:8767/en/ebooki.html');await p.locator('#ebook-open').click();await p.locator('#ebook-password').fill('00000000');await p.locator('#ebook-password-form button[type=submit]').click();await grab('#ebook-password-error');
await p.goto('http://127.0.0.1:8767/en/kolorowanki.html');await p.evaluate(()=>window.print=()=>window.testPrint=true);await p.locator('[data-print]').first().click();await p.waitForFunction(()=>window.testPrint,{timeout:10000});
for(const width of [1365,820,390,320]){await p.setViewportSize({width,height:850});await p.goto('http://127.0.0.1:8767/en/index.html');await p.waitForTimeout(100);const boxes=await p.evaluate(()=>['.brand','.language-switcher','.menu-btn'].map(s=>{let r=document.querySelector(s).getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom}}));assert(boxes[0].right<=boxes[1].left && boxes[1].right<=boxes[2].left,JSON.stringify({width,boxes}));assert(await p.locator('.language-switcher').isVisible());if(width===390)await p.waitForTimeout(1800);if(width===390)await p.screenshot({path:'/tmp/ewa-en-mobile.png'});}
await p.setViewportSize({width:1365,height:900});await p.goto('http://127.0.0.1:8767/en/index.html');await p.waitForTimeout(1800);await p.screenshot({path:'/tmp/ewa-en-desktop.png'});await p.locator('.language-switcher [lang=pl]').click();assert(!p.url().includes('/en/'));assert(await p.locator('.language-switcher').isVisible());await p.locator('.language-switcher [lang=en]').click();assert(p.url().includes('/en/'));assert(await p.locator('.language-switcher').isVisible());
const remaining=outputs.join('\n').replaceAll('Miłek','Milek');assert(!/[ąćęłńóśźż]/i.test(remaining),'Polish text remains in interaction output');assert.deepEqual(errors,[]);
const first=await b.newContext();const firstPage=await first.newPage();await firstPage.goto('http://127.0.0.1:8767/en/index.html');await firstPage.locator('.language-choice [data-lang=en]').click();assert(await firstPage.locator('.language-switcher').isVisible());await firstPage.reload();assert.equal(await firstPage.locator('.language-choice').count(),0);await first.close();
fs.writeFileSync('/tmp/ewa-interaction-text.txt',outputs.join('\n---\n'));console.log(JSON.stringify({status:'passed',errors,checks:'Admin errors and every calculator, active/retired photo IDs, gallery, offers, ebook error, print, switcher and 4 viewport sizes'}));await b.close()})().catch(e=>{console.error(e);process.exit(1)})
