"""Offline PL/EN build. Source pages stay Polish; translations are full phrases."""
from pathlib import Path
from html.parser import HTMLParser
from html import escape
import json,re
from urllib.parse import parse_qsl,urlencode
R=Path(__file__).resolve().parent.parent
D=json.loads((R/'data/i18n/en.json').read_text())
MISSING=set()
def tr(s,strict=False):
 key=' '.join(s.split())
 if key in D:
  return s[:len(s)-len(s.lstrip())]+D[key]+s[len(s.rstrip()):]
 if strict and re.search(r'[A-Za-ząćęłńóśźż]',key):MISSING.add(key)
 return s
class EnglishPage(HTMLParser):
 def __init__(self):super().__init__(convert_charrefs=True);self.out=[];self.skip=False;self.schema=False
 def handle_starttag(self,t,a):
  if t in ('script','style'):self.skip=True
  self.schema=t=='script' and dict(a).get('type')=='application/ld+json'
  attrs=[];meta=dict(a).get('name',dict(a).get('property',''))
  for k,v in a:
   if v is not None:
    if k in ('alt','title','aria-label','placeholder') or (k=='value' and dict(a).get('type') in ('submit','button')):v=tr(v,True)
    if k=='href' and v.startswith('mailto:') and '?' in v:
     address,query=v.split('?',1);v=address+'?'+urlencode([(k,tr(x,True) if k in ('subject','body') else x) for k,x in parse_qsl(query)])
    if t=='html' and k=='lang':v='en'
    if t=='meta' and k=='content':
     if meta in ('description','og:title','og:description','twitter:title','twitter:description'):v=tr(v,True)
     if meta=='og:locale':v='en_GB'
     if meta=='og:url':v=v.replace('https://ewamilek.pl/','https://ewamilek.pl/en/')
    if k in ('src','href','poster') and v and not re.match(r'(?:[a-z]+:|//|#|/)',v):
     if not re.match(r'[^?#]*\.html(?:[?#]|$)',v):v='../'+v
    if t=='link' and k=='href' and dict(a).get('rel')=='canonical':v=v.replace('https://ewamilek.pl/','https://ewamilek.pl/en/')
   attrs.append(k if v is None else f'{k}="{escape(v,quote=True)}"')
  self.out.append('<'+t+(' '+' '.join(attrs) if attrs else '')+'>')
  if t=='head':self.out.append('\n<script src="../assets/js/english.js"></script>\n')
 def handle_startendtag(self,t,a):self.handle_starttag(t,a)
 def handle_endtag(self,t):
  self.out.append('</'+t+'>')
  if t in ('script','style'):self.skip=False;self.schema=False
 def handle_data(self,s):
  if self.schema:
   def localize(v):
    if isinstance(v,dict):return {k:localize(x) for k,x in v.items()}
    if isinstance(v,list):return [localize(x) for x in v]
    if isinstance(v,str):
     if v in ('pl','pl-PL'):return 'en-GB'
     if v.startswith('https://ewamilek.pl/') and ('assets/' not in v and 'facebook-zdjecia' not in v):return v.replace('https://ewamilek.pl/','https://ewamilek.pl/en/')
     return tr(v)
    return v
   s=json.dumps(localize(json.loads(s)),ensure_ascii=False)
  self.out.append(s if self.skip else escape(tr(s,True),quote=False))
 def handle_comment(self,s):self.out.append('<!--'+s+'-->')
 def handle_decl(self,s):self.out.append('<!'+s+'>')
def alternates(name):
 tail='' if name=='index.html' else name
 return f'<link rel="alternate" hreflang="pl" href="https://ewamilek.pl/{tail}">\n<link rel="alternate" hreflang="en" href="https://ewamilek.pl/en/{tail}">\n'
def build_english():
 output={}
 for f in R.glob('*.html'):
  source=re.sub(r'<link\b(?=[^>]*hreflang=)[^>]*>\s*','',f.read_text())
  p=EnglishPage();p.feed(source)
  content=''.join(p.out).replace('</head>',alternates(f.name)+'</head>')
  if f.name=='ebooki.html':content=content.replace('<button class="btn btn-primary" id="ebook-open"', '<p class="source-language-note">The downloadable e-book is the original Polish-language edition.</p><button class="btn btn-primary" id="ebook-open"')
  if f.name=='kolorowanki.html':content=content.replace('<h2>Colouring pages from Ewa', '<p class="source-language-note">Original artwork and downloads retain their original lettering and artist signatures.</p><h2>Colouring pages from Ewa')
  output[f.name]=content
 if MISSING:raise ValueError('Missing English phrases:\n'+'\n'.join(sorted(MISSING)))
 (R/'en').mkdir(exist_ok=True)
 for name,content in output.items():
  (R/'en'/name).write_text(content)
  f=R/name;s=re.sub(r'<link\b(?=[^>]*hreflang=)[^>]*>\s*','',f.read_text());f.write_text(s.replace('</head>',alternates(name)+'</head>'))
 runtime=(R/'scripts/english-runtime.js').read_text()
 (R/'assets/js/english.js').write_text('/* Generated by scripts/i18n.py. Edit data/i18n/en.json and scripts/english-runtime.js. */\nconst EWA_EN='+json.dumps(D,ensure_ascii=False)+';\n'+runtime)
if __name__=='__main__':build_english()
